# Site settings
title: Cwyark
description: "I'm Chester, an enginner, a hjkl vimer"
url: 'https://cwyark.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: cwyark@gmail.com
  twitter_username: cwyark
  facebook_username: tsengyushen
  github_username:  cwyark
  linkedin_username:  chester-tseng-996ab676

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-srcset']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
