version: '3'

services:
  site: 
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - bundles:/usr/local/bundle
      - site:/srv/jekyll/_site
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000

volumes:
  site:
  bundles:
